import { ParserRuleContext } from 'antlr4';
import AttributedObject from './AttributedObject';
import AggregateExpressionVisitor from './parser/AggregateExpressionVisitor';
export default class ExpressionVisitorFacade extends AggregateExpressionVisitor {
    visitChildren(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visit(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitCompilationUnit(ctx: ParserRuleContext): Promise<AttributedObject | null> | AttributedObject;
    visitLogicalAndNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitBitwiseOrNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitBitwiseXorNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitNENode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitConditionalNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitModNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitLogicalNotNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitEQNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject | AttributedObject;
    visitBitwiseAndNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitGENode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitUnsignedRightShiftNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitAddNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitLTNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitBitwiseNotNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitSubtractNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitGTNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitValueReferenceNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitRegexMatchNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitLiteralExpression(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject | AttributedObject;
    visitFunctionNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitRightShiftNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitDivNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitLeftShiftNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitExpressionNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitLENode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitLogicalOrNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitMulNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitUnaryNode(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitFunctionExpression(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitFunctionReferenceExpression(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitActionReferenceExpression(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitEventReferenceExpression(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitReferenceSchema(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitReferenceServer(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitReferenceContextMask(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitReferenceEntity(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitReferenceRow(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitReferenceProperty(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitValueReference(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitArguments(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitAgIdentifier(ctx: ParserRuleContext): Promise<AttributedObject> | AttributedObject;
    visitLongConstNode(ctx: ParserRuleContext): AttributedObject;
    visitFloatConstNode(ctx: ParserRuleContext): AttributedObject;
    visitStringConstNode(ctx: ParserRuleContext): AttributedObject;
    visitTrueNode(ctx: ParserRuleContext): AttributedObject;
    visitFalseNode(ctx: ParserRuleContext): AttributedObject;
    visitNullNode(ctx: ParserRuleContext): AttributedObject;
}
