import GenericActionCommand from '../GenericActionCommand';
import TableFormat from '../../datatable/TableFormat';
import DataTable from '../../datatable/DataTable';
export default class SelectEntities extends GenericActionCommand {
    static readonly CF_TYPES: string;
    static readonly CF_ROOT: string;
    static readonly CF_DEFAULT: string;
    static readonly CF_EXPANDED: string;
    static readonly CF_SHOW_CHILDREN: string;
    static readonly CF_ALLOW_MASKS: string;
    static readonly CF_SHOW_VARS: string;
    static readonly CF_SHOW_FUNCS: string;
    static readonly CF_SHOW_EVENTS: string;
    static readonly CF_SHOW_FIELDS: string;
    static readonly CF_SINGLE_SELECTION: string;
    static readonly CF_TYPES_TYPE: string;
    static readonly RF_REFERENCE: string;
    private static readonly CFT_SELECT_ENTITIES_TYPES;
    static readonly CFT_SELECT_ENTITIES: TableFormat;
    static __static_initializer_0(): void;
    static readonly RFT_SELECT_ENTITIES: TableFormat;
    private contextTypes;
    private rootContext;
    private defaultContext;
    private expandedContext;
    private showChildren;
    private allowMasks;
    private showVars;
    private showFuncs;
    private showEvents;
    private showFields;
    private singleSelection;
    private static _init;
    static initialize(): void;
    constructor(type?: string, titleOrFormat?: string | TableFormat, responseFormat?: TableFormat | null);
    static createSelectEntitiesWithDataTable(type: string, title: string, parameters: DataTable): SelectEntities;
    static createSelectEntities(title: string, contextTypes: Array<string> | null, rootContext: string, defaultContext: string | null, expandedContext: string | null, showChildren: boolean, allowMasks: boolean, showVars: boolean, showFuncs: boolean, showEvents: boolean, showFields: boolean, singleSelection: boolean): SelectEntities;
    protected constructParameters(): DataTable;
    getContextTypes(): Array<string> | null;
    setContextTypes(contextTypes: Array<string> | null): void;
    getRootContext(): string | null;
    setRootContext(rootContext: string): void;
    getDefaultContext(): string | null;
    setDefaultContext(defaultContext: string | null): void;
    getExpandedContext(): string | null;
    setExpandedContext(expandedContext: string | null): void;
    isShowChildren(): boolean;
    setShowChildren(showChildren: boolean): void;
    isAllowMasks(): boolean;
    setAllowMasks(allowMasks: boolean): void;
    isShowVars(): boolean;
    setShowVars(showVars: boolean): void;
    isShowFuncs(): boolean;
    setShowFuncs(showFuncs: boolean): void;
    isShowEvents(): boolean;
    setShowEvents(showEvents: boolean): void;
    isShowFields(): boolean;
    setShowFields(showFields: boolean): void;
    isSingleSelection(): boolean;
    setSingleSelection(singleSelection: boolean): void;
}
