export default class EventFilterContextConstants {
    static readonly V_RULES: string;
    static readonly V_PRIMARY_FIELDS: string;
    static readonly V_ADDITIONAL_FIELDS: string;
    static readonly V_CUSTOM_HIGHLIGHTING: string;
    static readonly V_HISTORY_SETTINGS: string;
    static readonly F_GET_PARAMETERS: string;
    static readonly F_ACTIVATE: string;
    static readonly F_ADDITIONAL_REFERENCES: string;
    static readonly A_CONFIGURE_FROM_LOG: string;
    static readonly A_PARAMETERIZE: string;
    static readonly VF_ADDITIONAL_FIELDS_NAME: string;
    static readonly VF_ADDITIONAL_FIELDS_DESCRIPTION: string;
    static readonly VF_ADDITIONAL_FIELDS_EDESCS: string;
    static readonly VF_ADDITIONAL_FIELDS_SHOWN: string;
    static readonly VF_CUSTOM_HIGHLIGHTING_MASK: string;
    static readonly VF_CUSTOM_HIGHLIGHTING_EVENT: string;
    static readonly VF_CUSTOM_HIGHLIGHTING_EXPRESSION: string;
    static readonly VF_CUSTOM_HIGHLIGHTING_LEVEL: string;
    static readonly VF_CUSTOM_HIGHLIGHTING_COLOR: string;
    static readonly FIF_GET_PARAMETERS_REALTIME: string;
    static readonly FIF_GET_PARAMETERS_EDITABLE_BINDINGS: string;
    static readonly FIF_ACTIVATE_REALTIME: string;
    static readonly FIF_ACTIVATE_LISTENER: string;
    static readonly FIF_ACTIVATE_PARAMETERS: string;
    static readonly FIF_ACTIVATE_DEFAULT_CONTEXT: string;
    static readonly STATUS_NORMAL: number;
    static readonly STATUS_DEFAULT: number;
}
