import AbstractOperation from './AbstractOperation';
import DataTable from '../../datatable/DataTable';
import UserSettings from '../../util/UserSettings';
import StepActionInterceptor from '../StepActionInterceptor';
import RemoteConnector from '../../util/RemoteConnector';
import ActionExecutor from './ActionExecutor';
import ActionWorker from './ActionWorker';
import Context from '../../context/Context';
import Runnable from '../../util/java/Runnable';
export default class InvokeActionOperation extends AbstractOperation {
    protected readonly actionName: string;
    protected readonly userSettings: UserSettings | null;
    protected readonly stepInterceptor: StepActionInterceptor;
    protected readonly actionId: string | null;
    private connector;
    private actionWorker;
    private default;
    private enabled;
    private executionGroup;
    private executor;
    private defaultParameters;
    constructor(name: string, description: string, iconId: string, group: string, context: Context<any, any>, invokerContext: Context<any, any>, userSettings?: UserSettings | null, interceptor?: StepActionInterceptor | null, actionId?: string | null);
    getConnector(): RemoteConnector | null;
    setConnector(connector: RemoteConnector): void;
    getDefaultParameters(): DataTable | null;
    getExecutionGroup(): number;
    interrupt(): void;
    getExecutor(): ActionExecutor | null;
    setExecutor(executor: ActionExecutor): void;
    addInterruptionListener(listener: Runnable): void;
    removeInterruptionListener(listener: Runnable): void;
    execute(params?: DataTable | null): Promise<void>;
    private getCallerController;
    isEnabled(): boolean;
    isDefault(): boolean;
    getActionWorker(): ActionWorker | null;
}
