import Command from '../communication/Command';
export default abstract class AggreGateCommand extends Command {
    static readonly START_CHAR: number;
    static readonly END_CHAR: number;
    static readonly COMMAND_CODE_MESSAGE: string;
    static readonly COMMAND_CODE_REPLY: string;
    static readonly MESSAGE_CODE_START: string;
    static readonly MESSAGE_CODE_OPERATION: string;
    static readonly MESSAGE_CODE_EVENT: string;
    static readonly MESSAGE_CODE_COMPRESSION: string;
    static readonly COMMAND_OPERATION_GET_VAR: string;
    static readonly COMMAND_OPERATION_SET_VAR: string;
    static readonly COMMAND_OPERATION_CALL_FUNCTION: string;
    static readonly COMMAND_OPERATION_ADD_EVENT_LISTENER: string;
    static readonly COMMAND_OPERATION_REMOVE_EVENT_LISTENER: string;
    static readonly INDEX_COMMAND_CODE: number;
    static readonly INDEX_ID: number;
    static readonly INDEX_MESSAGE_CODE: number;
    static readonly INDEX_START_PROTOCOL_VERSION: number;
    static readonly INDEX_START_COMPRESSION: number;
    static readonly INDEX_PROTOCOL_VERSION: number;
    static readonly INDEX_OPERATION_CODE: number;
    static readonly INDEX_OPERATION_CONTEXT: number;
    static readonly INDEX_OPERATION_TARGET: number;
    static readonly INDEX_OPERATION_MESSAGE_DATA_TABLE: number;
    static readonly INDEX_OPERATION_MESSAGE_QUEUE_NAME: number;
    static readonly INDEX_OPERATION_MESSAGE_FLAGS: number;
    static readonly INDEX_OPERATION_LISTENER_CODE: number;
    static readonly INDEX_OPERATION_FILTER: number;
    static readonly INDEX_OPERATION_FINGERPRINT: number;
    static readonly INDEX_EVENT_CONTEXT: number;
    static readonly INDEX_EVENT_NAME: number;
    static readonly INDEX_EVENT_LEVEL: number;
    static readonly INDEX_EVENT_ID: number;
    static readonly INDEX_EVENT_LISTENER: number;
    static readonly INDEX_EVENT_DATA_TABLE: number;
    static readonly INDEX_EVENT_TIMESTAMP: number;
    static readonly INDEX_REPLY_CODE: number;
    static readonly INDEX_REPLY_MESSAGE: number;
    static readonly INDEX_REPLY_DETAILS: number;
    static readonly INDEX_DATA_TABLE_IN_REPLY: number;
    static readonly CLIENT_COMMAND_SEPARATOR: string;
    private static GENERATED_ID;
    private static readonly MAX_PRINTED_LENGTH;
    toString(): string;
    static generateId(): string;
    static convert(unicode: string): string;
}
