import AggreGateBean from '../datatable/AggreGateBean';
import TableFormat from '../datatable/TableFormat';
import DataRecord from '../datatable/DataRecord';
export default class DashboardProperties extends AggreGateBean {
    static readonly FIELD_NAME: string;
    static readonly FIELD_DESCRIPTION: string;
    static readonly FIELD_LAYOUT: string;
    static readonly FIELD_COLUMNS: string;
    static readonly FIELD_CLOSABLE: string;
    static readonly FIELD_CLEANUP: string;
    static readonly FIELD_STORAGE_CONTEXT: string;
    static readonly FIELD_STORAGE_CLASS: string;
    static readonly FIELD_STORAGE_SESSION_ID: string;
    static readonly FIELD_DEFAULT_EVENT: string;
    static readonly FIELD_STORAGE_INSTANCE_ID: string;
    static readonly FIELD_DASHBOARD_CONTEXT: string;
    static readonly FIELD_ELEMENT_ID: string;
    static readonly FIELD_PARENT_ELEMENT_ID: string;
    static readonly FIELD_CLOSE_DASHBOARD_ON_REOPEN: string;
    static readonly LAYOUT_DOCKABLE: number;
    static readonly LAYOUT_SCROLLABLE: number;
    static readonly LAYOUT_GRID: number;
    private static init;
    static FORMAT: TableFormat;
    static _static_initializer_0(): void;
    private name;
    private description;
    private layout;
    private columns;
    private closable;
    private cleanup;
    private storageContext;
    private storageClass;
    private storageSessionId;
    private defaultEvent;
    private dashboardContext;
    private elementId;
    private parentElementId;
    private closeDashboardOnReopen;
    isCloseDashboardOnReopen(): boolean | null;
    setCloseDashboardOnReopen(closeDashboardOnReopen: boolean): void;
    constructor(data?: DataRecord);
    createWith(name: string, description: string, layout?: number): void;
    getName(): string | null;
    setName(name: string): void;
    getDescription(): string | null;
    setDescription(description: string): void;
    getLayout(): number | null;
    setLayout(layout: number): void;
    getColumns(): number | null;
    setColumns(columns: number): void;
    setClosable(closable: boolean): void;
    isCleanup(): boolean | null;
    setCleanup(cleanup: boolean): void;
    isClosable(): boolean | null;
    toString(): string | null;
    getStorageContext(): string | null;
    setStorageContext(storageContext: string): void;
    getStorageClass(): string | null;
    setStorageClass(className: string): void;
    getStorageSessionId(): number | null;
    setStorageSessionId(storageSessionId: number): void;
    getFieldStorageSessionId(): string | null;
    getDefaultEvent(): string | null;
    setDefaultEvent(defaultEvent: string): void;
    getDashboardContext(): string | null;
    setDashboardContext(dashboardContextString: string): void;
    getElementId(): string | null;
    setElementId(elementIdString: string): void;
    getParentElementId(): string | null;
    setParentElementId(parentElementId: string): void;
    copy(): DashboardProperties;
    copyWithNameAndDescription(nameString: string, descriptionString: string): DashboardProperties;
}
