import JObject from './java/JObject';
import TimeUnit from './TimeUnit';
export default class TimeHelper extends JObject {
    static readonly SECOND_IN_MS: number;
    static readonly MINUTE_IN_MS: number;
    static readonly HOUR_IN_MS: number;
    static readonly DAY_IN_MS: number;
    static readonly WEEK_IN_MS: number;
    static readonly MONTH_IN_MS: number;
    static readonly QUARTER_IN_MS: number;
    static readonly YEAR_IN_MS: number;
    static readonly MINUTE_IN_SECONDS: number;
    static readonly HOUR_IN_SECONDS: number;
    static readonly DAY_IN_SECONDS: number;
    static readonly WEEK_IN_SECONDS: number;
    static readonly MONTH_IN_SECONDS: number;
    static readonly QUARTER_IN_SECONDS: number;
    static readonly YEAR_IN_SECONDS: number;
    static readonly MILLISECOND: number;
    static readonly SECOND: number;
    static readonly MINUTE: number;
    static readonly HOUR: number;
    static readonly DAY: number;
    static readonly WEEK: number;
    static readonly MONTH: number;
    static readonly QUARTER: number;
    static readonly YEAR: number;
    static readonly NAME_MILLISECOND: string;
    static readonly NAME_MS: string;
    static readonly NAME_SECOND: string;
    static readonly NAME_SEC: string;
    static readonly NAME_S: string;
    static readonly NAME_MINUTE: string;
    static readonly NAME_MIN: string;
    static readonly NAME_M: string;
    static readonly NAME_HOUR: string;
    static readonly NAME_HR: string;
    static readonly NAME_H: string;
    static readonly NAME_DAY: string;
    static readonly NAME_D: string;
    static readonly NAME_WEEK: string;
    static readonly NAME_W: string;
    static readonly NAME_MONTH: string;
    static readonly NAME_YEAR: string;
    static readonly NAME_Y: string;
    static readonly CALENDAR_YEAR: number;
    static readonly CALENDAR_QUARTER: number;
    static readonly CALENDAR_MONTH: number;
    static readonly CALENDAR_WEEK_OF_YEAR: number;
    static readonly CALENDAR_DATE: number;
    static readonly CALENDAR_DAY_OF_YEAR: number;
    static readonly CALENDAR_DAY_OF_WEEK: number;
    static readonly CALENDAR_HOUR: number;
    static readonly CALENDAR_MINUTE: number;
    static readonly CALENDAR_SECOND: number;
    static readonly CALENDAR_MILLISECOND: number;
    static MILLISECOND_UNIT: TimeUnit;
    static SECOND_UNIT: TimeUnit;
    static MINUTE_UNIT: TimeUnit;
    static HOUR_UNIT: TimeUnit;
    static DAY_UNIT: TimeUnit;
    static WEEK_UNIT: TimeUnit;
    static MONTH_UNIT: TimeUnit;
    static QUARTER_UNIT: TimeUnit;
    static YEAR_UNIT: TimeUnit;
    private static NAMED_UNITS;
    private static UNITS;
    private static REVERSED_UNITS;
    static getTimeUnitByName(name: string): TimeUnit;
    static getUnits(): Array<TimeUnit>;
    static getReversedUnits(): Array<TimeUnit>;
    static initialize(): void;
    static setTimeZone(date: Date, timeZone: string): Date;
}
