import Context from '../context/Context';
import DataTable from '../datatable/DataTable';
import ServerActionInput from './ServerActionInput';
import TableFormat from '../datatable/TableFormat';
import ActionIdentifier from './ActionIdentifier';
import GenericActionCommand from './GenericActionCommand';
import GenericActionResponse from './GenericActionResponse';
import ActionExecutionMode from './ActionExecutionMode';
import ErrorCollector from '../util/ErrorCollector';
import CallerController from '../context/CallerController';
import Class from '../util/java/Class';
export default abstract class ActionUtils {
    static readonly CMD_SHOW_MESSAGE: string;
    static readonly CMD_CONFIRM: string;
    static readonly CMD_EDIT_DATA: string;
    static readonly CMD_EDIT_PROPERTIES: string;
    static readonly CMD_EDIT_WIDGET: string;
    static readonly CMD_EDIT_PROCESS_CONTROL_PROGRAM: string;
    static readonly CMD_EDIT_WORKFLOW: string;
    static readonly CMD_LAUNCH_WORKFLOW: string;
    static readonly CMD_LAUNCH_WIDGET: string;
    static readonly CMD_LAUNCH_PROCESS_CONTROL_PROGRAM: string;
    static readonly CMD_BROWSE: string;
    static readonly CMD_SHOW_EVENT_LOG: string;
    static readonly CMD_SHOW_ERROR: string;
    static readonly CMD_EDIT_REPORT: string;
    static readonly CMD_SHOW_REPORT: string;
    static readonly CMD_SHOW_GUIDE: string;
    static readonly CMD_SELECT_ENTITIES: string;
    static readonly CMD_EDIT_TEXT: string;
    static readonly CMD_EDIT_CODE: string;
    static readonly CMD_SHOW_SYSTEM_TREE: string;
    static readonly CMD_SHOW_HTML_SNIPPET: string;
    static readonly CMD_ACTIVATE_DASHBOARD: string;
    static readonly CMD_SHOW_DIFF: string;
    static readonly CMD_CLOSE_DASHBOARD: string;
    static readonly CMD_OPEN_GRID_DASHBOARD: string;
    static readonly CMD_EDIT_GRID_DASHBOARD: string;
    static readonly RESPONSE_OK: string;
    static readonly RESPONSE_SAVED: string;
    static readonly RESPONSE_CLOSED: string;
    static readonly RESPONSE_ERROR: string;
    static readonly INDEX_NORMAL: number;
    static readonly INDEX_LOWER: number;
    static readonly INDEX_LOW: number;
    static readonly INDEX_VERY_LOW: number;
    static readonly INDEX_LOWEST: number;
    static readonly YES_OPTION: number;
    static readonly NO_OPTION: number;
    static readonly CANCEL_OPTION: number;
    static readonly OK_OPTION: number;
    static readonly CLOSED_OPTION: number;
    static readonly QUESTION_MESSAGE: number;
    static readonly YES_NO_OPTION: number;
    static readonly YES_NO_CANCEL_OPTION: number;
    static readonly OK_CANCEL_OPTION: number;
    static readonly FORMAT_DND_ACTION: TableFormat;
    static readonly FORMAT_NORMAL_ACTION: TableFormat;
    private static ACTION_INITIALIZER;
    static readonly COMMANDS: Map<string, Class>;
    static readonly DESCRIPTIONS: Map<string, string>;
    static __static_initializer_0(): void;
    private static _init;
    static initialize(): void;
    static readonly FIELD_ACTION_EXECUTION_PARAMETERS: string;
    static readonly FIELD_ACTION_FROM_CONTEXT: string;
    static readonly FIELD_ACTION_TARGET_CONTEXT: string;
    static checkResponseCode(result: string): void;
    static createDndActionParametersContext(acceptedContext: Context<any, any>): DataTable;
    static createDndActionParameters(accepterContextPath: string): DataTable;
    static createActionInput(executionParameters: DataTable): ServerActionInput;
    static initActionCreate(context: Context<any, any>, actionName: string, initialParameters: ServerActionInput, inputData: DataTable, mode: ActionExecutionMode, callerController: CallerController): Promise<ActionIdentifier>;
    static initAction(context: Context<any, any>, actionName: string, initialParameters: ServerActionInput, inputData: DataTable, environment: Map<string, any> | null, mode: ActionExecutionMode, callerController: CallerController, collector: ErrorCollector | null): Promise<ActionIdentifier>;
    static stepAction(context: Context<any, any>, actionId: Promise<ActionIdentifier>, actionResponse: GenericActionResponse | null, callerController: CallerController): Promise<GenericActionCommand | null>;
}
