import ActionCommand from './ActionCommand';
import ActionResponse from './ActionResponse';
import StringIdentifier from './StringIdentifier';
import JObject from '../util/java/JObject';
import RequestIdentifier from './RequestIdentifier';
import DataTable from '../datatable/DataTable';
import TableFormat from '../datatable/TableFormat';
export default class GenericActionCommand extends JObject implements ActionCommand {
    protected parameters: DataTable | null;
    private requestId;
    private responseFormat;
    private interactive;
    private type;
    private title;
    private batchEntry;
    private last;
    constructor(type: string, titleOrFormat?: string | TableFormat | null, responseFormat?: TableFormat | null);
    static createWithParameters(type: string, title: string, parameters: DataTable | null, format?: TableFormat): GenericActionCommand;
    getType(): string;
    setResponseFormat(responseFormat: TableFormat): void;
    getResponseFormat(): TableFormat | null;
    protected setTitle(title: string): void;
    getTitle(): string | null;
    setType(type: string): void;
    setLast(last: boolean): void;
    isLast(): boolean;
    clone(): this;
    getRequestId(): StringIdentifier | null;
    isBatchEntry(): boolean;
    isInteractive(): boolean;
    isResponseValid(actionRequest: ActionResponse): boolean;
    setBatchEntry(batchEntry: boolean): void;
    setParameters(parameters: DataTable | null): void;
    getParameters(): DataTable | null;
    protected constructParameters(): DataTable | null;
    setRequestId(requestId: RequestIdentifier | null): void;
    setInteractive(interactive: boolean): void;
    toString(): string;
    equals(obj: any): boolean;
}
