import DataTable from '../datatable/DataTable';
import ServerAction from './ServerAction';
import ActionDefinition from './ActionDefinition';
import ServerActionInput from './ServerActionInput';
import CallerController from '../context/CallerController';
import ServerContext from '../server/ServerContext';
import RequestIdentifier from './RequestIdentifier';
import Reference from '../expression/Reference';
import GenericActionCommand from './GenericActionCommand';
import GenericActionResponse from './GenericActionResponse';
import EditDataMerger from './EditDataMerger';
import DashboardProperties from '../util/DashboardProperties';
import WindowLocation from '../util/WindowLocation';
import Context from '../context/Context';
import EditData from './command/EditData';
import EntityList from '../context/EntityList';
import ContextManager from '../context/ContextManager';
export default class ServerActionCommandProcessor {
    private action;
    constructor(action: ServerAction);
    static getExecutionParameter(input: DataTable, name: string): DataTable | null;
    fetchDnDSourceContexts(title: string, actionDefinition: ActionDefinition, actionParams: ServerActionInput, callerController: CallerController, expandedContext?: string | null): Array<ServerContext>;
    getDnDSourceContext(actionParams: ServerActionInput, callerController: CallerController): ServerContext | null;
    send(cmd: GenericActionCommand): GenericActionResponse | null;
    editDataWithTitle(title: string, data: DataTable, iconId?: string | null, helpId?: string | null, help?: string | null): DataTable | null;
    editDataWithToolbar(id: RequestIdentifier | null, merger: EditDataMerger | null, group: boolean, title: string, data: DataTable, useDockableFrame?: boolean, readonly?: boolean, iconId?: string | null, helpId?: string | null, help?: string | null, defaultContext?: Context<any, any> | null, location?: WindowLocation | null, dashboard?: DashboardProperties | null, expression?: string | null, period?: number | null): DataTable | null;
    editData(id: RequestIdentifier | null, merger: EditDataMerger | null, group: boolean, title: string, data: DataTable, useDockableFrame: boolean, readonly: boolean, iconId: string | null, helpId: string | null, help: string | null, defaultContext: Context<any, any> | null, location: WindowLocation | null, dashboard: DashboardProperties | null, expression: string | null, period: number | null, showToolbar: boolean, showHeader: boolean | null, showLineNumbers: boolean | null, horizontalScrolling: boolean | null): DataTable | null;
    editDataCmd(cmd: EditData, merger: EditDataMerger | null): DataTable | null;
    protected editTemplate(type: string, title: string, defaultContext: string, widgetContext: string, widget: string, editMode: number): string | null;
    editWidget(title: string, defaultContext: string, widgetContext: string, widget: string): string | null;
    editProcessControlProgram(title: string, defaultContext: string, widgetContext: string, widget: string, editMode: number): string | null;
    editWorkflow(title: string, defaultContext: string, widgetContext: string, widget: string): string | null;
    browse(url: string): void;
    launchProcessControlProgram(title: string, widgetContext: string, defaultContext: string, encodedWidgetTemplate: string, location: WindowLocation, dp: DashboardProperties, input: DataTable): GenericActionResponse | null;
    showError(title: string, level: number, message: string, ex: Error): void;
    showMessage(title: string | undefined, message: string, level?: number): void;
    showReport(title: string, reportData: any, location: WindowLocation, dashboard: DashboardProperties, reportFormat: string): void;
    showEventLog(title: string, eventList: EntityList, showRealtime: boolean, showHistory: boolean, preloadHistory: boolean, showContexts: boolean, showNames: boolean, showLevels: boolean, showAcknowledgements: boolean, showEnrichments: boolean, customListenerCode: number, location: WindowLocation, dashboard: DashboardProperties): number | null;
    showGuide(title: string, invokerContext: string, macroName: string): DataTable | null;
    selectEntities(id: RequestIdentifier, title: string, contextTypes: Array<string> | null, rootContext: string, defaultContext: string | null, expandedContext: string | null, showChildren: boolean, allowMasks: boolean, showVars: boolean, showFuncs: boolean, showEvents: boolean, showFields: boolean, singleSelection: boolean): Array<Reference>;
    editText(title: string, text: string, mode: string): string | null;
    editCode(title: string, code: string, mode: string): string | null;
    showSystemTree(title: string, roots: Context<Context<any, any>, ContextManager<any>> | Array<string>): void;
    activateDashboard(nameString: string, parameters: DataTable): void;
    editDashboard(parameters: DataTable): void;
}
